### ISSUE TITLE
Adding/Replacing a block by another

### ISSUE THREAD

**Issue by 0xNyaku** [MrYotic/MinecraftESP#2]
What if im trying to ESP Stone blocks for example, what should i do?

**Comment by MrYotic** [comment]
My code can esp only title-blocks, like chests, spawners, heads and etc, because non-title blocks, like stone, bricks, grass and etc all are render in one phase, so you will not be able to get their matrix

**Comment by 0xNyaku** [comment]
I see, thats usefull, how do you get a blocks matrix tho? sorry for those questions

**Comment by MrYotic** [comment]
For non-title blocks?

**Comment by 0xNyaku** [comment]
No, title blocks

**Comment by MrYotic** [comment]
Every block has own scale and transform. So when minecraft called hooked by you function with arguments that are used for a specific block you can draw esp or save matrix data for future manipulation

**Comment by 0xNyaku** [comment]
Okaay, thanks for the help, i appreciate it, ill try to find a ready client or figure out an other way to esp a specific block

**Comment by Curlypla** [comment]
> For non-title blocks?

So there's no way of distinguishing blocks for non-title blocks ?

**Comment by MrYotic** [comment]
I don’t understand the question, why differentiate them? Non-title doesn't have separate render

**Comment by MrYotic** [comment]
> So there's no way of distinguishing blocks for non-title blocks ?

I don’t understand the question, why differentiate them? Non-title doesn't have separate render
